import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');
await page.waitForFunction(()=>window.__cube?.snapshot().fps>0);
await page.getByRole('button',{name:'6面完成',exact:true}).click();
const snap=()=>page.evaluate(()=>window.__cube.snapshot());
const initial=(await snap()).pieces;
const point=await page.evaluate(()=>window.__cube.tilePoint(0,7));
await page.mouse.click(point.x,point.y);
assert.ok((await snap()).selection,'pointer picks tile');
await page.keyboard.press('w');await page.waitForTimeout(350);
assert.equal((await snap()).history,1);
assert.notDeepEqual((await snap()).pieces,initial);
await page.getByRole('button',{name:'1手戻す'}).click();await page.waitForTimeout(800);
assert.deepEqual((await snap()).pieces,initial);
assert.equal((await snap()).solved.length,6);
assert.ok((await snap()).spacing<1.01);
await page.getByRole('button',{name:'3手だけ混ぜる'}).click();await page.waitForTimeout(950);
assert.equal((await snap()).history,3);
const rotatedTile=await page.evaluate(()=>window.__cube.tilePoint(0,7));
await page.mouse.click(rotatedTile.x,rotatedTile.y);
await page.getByRole('button',{name:'最初に戻す'}).click();
await page.getByRole('button',{name:'12手',exact:true}).click();
await page.getByRole('button',{name:'最初に戻す'}).click();
await page.waitForTimeout(350);
assert.equal((await snap()).busy,false);
assert.equal((await snap()).history,0,'reset cancels queued animation');
await page.getByRole('button',{name:'最初に戻す'}).click();await page.waitForTimeout(300);
assert.deepEqual((await snap()).pieces,initial);
await page.screenshot({path:'desktop-check.png'});
const desktop=await snap();
for(const keys of [['w','s'],['a','d'],['w','w','w','w'],['a','a','a','a']]){
 const target=await page.evaluate(()=>window.__cube.tilePoint(0,7));
 await page.mouse.click(target.x,target.y);
 for(const key of keys){await page.keyboard.press(key);await page.waitForTimeout(300);}
 assert.deepEqual((await snap()).pieces,initial,'fixed selection: '+keys.join(''));
}
await page.getByRole('button',{name:'最初に戻す'}).click();await page.waitForTimeout(300);
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);
const tile=await page.evaluate(()=>window.__cube.tilePoint(0,7));
const cdp=await page.context().newCDPSession(page);
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:tile.x,y:tile.y}]});
await page.waitForTimeout(250);
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:tile.x+60,y:tile.y}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
await page.waitForTimeout(350);
assert.equal((await snap()).history,1,'long press swipe');
await page.getByRole('button',{name:'採用イラストを見る'}).click();
await page.keyboard.press('w');await page.waitForTimeout(300);
assert.equal((await snap()).history,1,'modal blocks game keyboard');
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'mobile-check.png',fullPage:true});
console.log(JSON.stringify({desktopFPS:desktop.fps,mobileHistory:(await snap()).history,errors},null,2));
assert.deepEqual(errors,[]);
await browser.close();
